In [92]:
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(suppress = True)

In [26]:
def save_results(array):
    
    textfile = "convergence_plots.txt"
    
    with open(textfile, 'a') as the_file:
        the_file.write(str(array[0]))
        for i in range(1, len(array)):
            the_file.write("," + str(array[i]))
            
        the_file.write('\n')

In [94]:
def plotting(steepest, newtons, quasi, cgm, title, range_y, range_x):

    filepath = 'convergence_plots_f1.txt'  # TODO: add path to your data file here
    names = ["Steepest Descent", "Newton's Method", "Quasi-Newton's Method", "Conjugate Gradient Method"]  # TODO: add the names of each sorting method in the order they are saved in the text file
    
    x_steepest = list(range(1, len(steepest), 1))  # this is the range of input sizes tested
    x_newtons = list(range(1, len(newtons), 1))
    x_quasi = list(range(1, len(quasi), 1))
    x_cgm = list(range(1, len(cgm), 1))

    plt.plot(x_steepest, steepest, label="steepest descent")
    plt.plot(x_newtons, steepest, label="Newtons Method")
    plt.plot(x_quasi, steepest, label="Quasi-Newtons Method")
    plt.plot(x_cgm, steepest, label="Conjugate Gradient Method")

    plt.xticks(range(0, range_x))
    plt.yticks(range(0, range_y))
    plt.xlabel('No. of Iterations')
    plt.ylabel('convergence criteria')
    plt.title(title)
    plt.legend()
    plt.savefig("sorting_f1.pdf")
    plt.show()

## Test Functions

In [27]:
def f1(x):
    '''
    input: x, array with 50 elements
    returns: f1(x), a scalar
    '''

    sum = 0
    for i in range(50):
        sum+= (i+1) * x[i]**2
    return sum

def f2(x):
    '''
    input: x, array with 10 elements
    returns: f2(x), a scalar
    '''

    sum = 0
    for i in range(9):
        sum+= (100 * (x[i+1] - x[i]**2)**2 + (1-x[i])**2)
    return sum

def f3(x):
    '''
    input: x, array with 2 elements
    returns: f3(x), a scalar
    '''

    return (1.5 - x[0] + x[0] * x[1])**2 + (2.25 - x[0] + x[0]*x[1]**2)**2 + (2.625 - x[0] + x[0] * x[1] **3)**2

## Gradients and Hessians of Test functions

### 1)

In [28]:
def nabla_f1(x):
    """
    input: 1dim array of length 50
    returns: 1dim array of length 50
    """

    g = np.zeros(50)
    for i in range(50):
        g[i] = (i+1)*2*x[i]
    # return np.matrix(g).T
    return g

def ColumnVector_nabla_f1(x):
    return np.matrix(nabla_f1(x)).T

def Hessian_f1(x):
    """
    input: 1dim array of length 50
    returns: 50*50 np.array
    """
    
    H = np.zeros((50,50))
    for i in range(50):
        H[i,i] = (i+1) * 2
    return H

### 2)

In [29]:
def nabla_f2(x):
    """
    input: 1dim array of length 10
    returns: 1dim array of length 10
    """

    g = np.zeros(10)
    g[0] = -400 * x[0] * (x[1] - x[0]**2) - 2 * (1-x[0])
    for i in range(1,9):
        g[i] = -400 * x[i] * (x[i+1] - x[i]**2)-2*(1-x[i]) + 200 * (x[i] - x[i-1] **2)
    g[9] = 200 * (x[9] - x[8]**2)
    # return np.matrix(g).T
    return g

    
def ColumnVector_nabla_f2(x):
    return np.matrix(nabla_f2(x)).T

def Hessian_f2(x):
    """
    input: 1dim array of length 10
    returns: 10*10 np.array
    """

    H = np.zeros((10,10))
    H[0,0] = -400* (x[1] - x[0]**2) + 800*x[0] **2 + 2
    H[0,1] = -400*x[0]
    for i in range(1,9):
        H[i,i-1] = -400 * x[i-1]
        H[i,i] = -400 * (x[i+1] - x[i] **2) + 800 * x[i] **2 + 202
        H[i,i+1] = -400*x[i]
    H[9,8] = -400 * x[8]
    H[9,9] = 200
    return H


### 3)

In [5]:
def nabla_f3(x):
    """
    input: 1dim array of length 2
    returns: 1dim array of length 2
    """

    g = np.zeros(2)
    g[0] = 2 * (x[1] - 1)*(1.5 - x[0] + x[0]*x[1]) + 2*(x[1]**2 - 1)*(2.25 - x[0] + x[0]*x[1]**2) + 2 * (x[1]**3 - 1)*(2.625 - x[0] + x[0]*x[1]**3)
    g[1] = 2 * x[0] * (1.5 - x[0] + x[0]*x[1]) + 2*2*x[0]*x[1] * (2.25 - x[0] + x[0] * x[1]**2) + 2*3*x[0] * x[1]**2 * (2.625 - x[0] + x[0]*x[1]**3)
    # return np.matrix(g).T
    return g


def ColumnVector_nabla_f3(x):
    return np.matrix(nabla_f3(x)).T

def Hessian_f3(x):
    """
    input: 1dim array of length 10
    returns: 10*10 np.array
    """

    H = np.zeros((2,2))
    H[0,0] = 2*(x[1] - 1)**2 + 2 * (x[1]**2 - 1)**2 + 2 * (x[1]**3 - 1)**2
    H[0,1] = 4 * (x[1] - 1) + 8 * x[1] * (x[1]**2 - 1) + 12 * x[1]**2 * (x[1]**3 -1)
    H[1,0] = H[0,1]
    H[1,1] = 2 * x[0]**2 + 4 * x[0] * (2.25 - x[0] + x[0]*x[1]**2) + 8 * x[0]**2 * x[1]**2 + 12 * x[0]*x[1]*(2.625 - x[0] + x[0] * x[1]**3) + 12 * x[0]**2 * x[1]**4
    return H



# Methods

## Steepest Descent Method

### Functions

In [90]:
def backtracking(c, p, s, x, d, f, nabla_f):
    """ 
    Uses armijo condition
    """

    fx = f(x)
    nabla_fx = nabla_f(x)
    while f(x + s*d) > fx + c * s * np.dot(nabla_fx,d):
        s = p * s
    return s


def steepest_descent(f,nabla_f, x0, tol = 10**-8,max_iterations=500, s=1,c=0.1,p=0.5):
    """ 
    input: f, nabla_f, x0 (horizontal array)
    optional input: step size sBar (default =1), 
    returns: 1 dim array for x*
    """

    convergence_array = []
    x = x0
    k=0

    while k < max_iterations: #and np.linalg.norm(nabla_f(x))>tol:

        convergence_array.append( round(np.linalg.norm(nabla_f(x))) )
        d = - nabla_f(x)
        s = backtracking(c, p, s, x, d, f , nabla_f)
        x = x + s*d.T
        k+=1
    
    save_results(convergence_array)
    print("Number of iterations: ",k)
    return x

### Implementation

#### 1)

In [52]:
# INPUT 1 

input_1 = np.random.uniform(size = 50)	
print(input_1)

[0.64991849 0.94730415 0.40060988 0.79093935 0.26987874 0.85652596
 0.97795253 0.56360677 0.36217892 0.56188478 0.56708097 0.49833757
 0.44707358 0.47926448 0.70944324 0.52162782 0.45640138 0.2804654
 0.17693151 0.12423711 0.81573734 0.74676357 0.46845656 0.54139299
 0.39402755 0.50830677 0.38505158 0.17802597 0.32257911 0.41140944
 0.32529456 0.5757566  0.25297229 0.74784888 0.81488021 0.84921811
 0.25237798 0.71367885 0.64963017 0.72463995 0.36619568 0.6114949
 0.54708328 0.37376062 0.09252505 0.45648326 0.15942419 0.04807162
 0.3177259  0.64037283]


In [53]:
#INPUT 2 

input_2 = np.random.uniform(size = 50)	
print(input_2)

[0.79146055 0.17400109 0.82056397 0.81097525 0.72415685 0.74540807
 0.14064937 0.64405846 0.92497878 0.89954681 0.58856655 0.34819265
 0.60122683 0.36320353 0.64484212 0.25729907 0.69196579 0.64121698
 0.09056063 0.40596577 0.67310771 0.79250071 0.89353835 0.64872363
 0.63139162 0.82211607 0.24137624 0.15941148 0.86536332 0.09831182
 0.74441768 0.44079244 0.72782903 0.38543755 0.10909229 0.03216482
 0.84545341 0.98357649 0.19712631 0.20543625 0.80735861 0.98734296
 0.89509462 0.87715116 0.47788729 0.99139054 0.34712672 0.64454511
 0.45139616 0.30227373]


In [54]:
# INPUT 3 

input_3 = np.random.uniform(size = 50)	
print(input_3)

[0.7713435  0.58443835 0.34540331 0.13153973 0.40762056 0.04764066
 0.45745915 0.48409583 0.37103599 0.1780606  0.77897183 0.07937004
 0.13853753 0.94705606 0.99458236 0.12550029 0.8860437  0.00163024
 0.54888811 0.22321733 0.71452581 0.56408056 0.96479537 0.95053068
 0.31147123 0.40181206 0.56309071 0.6353681  0.50176353 0.86975278
 0.40008663 0.50550614 0.07360578 0.22679726 0.53587967 0.40939217
 0.46712985 0.47385337 0.75713009 0.18565328 0.3951978  0.89117444
 0.17288715 0.3727447  0.28249833 0.16669145 0.43032535 0.51641627
 0.65578151 0.59861357]


In [91]:
# FUNCTION 1 - INPUT 1 
x1_star = steepest_descent(f1,nabla_f1,input_1)
x1_star

Number of iterations:  500


array([0.00000008, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [25]:
# FUNCTION 1 - INPUT 2 

steepest_descent(f1,nabla_f1,input_2)


Number of iterations:  10000


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
# FUNCTION 1 - INPUT 3 

steepest_descent(f1,nabla_f1,input_3)

Number of iterations:  595


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0., -0., -0., -0., -0., -0., -0., -0., -0., -0.])

#### 2)

In [13]:
# INPUT 4,5,6

input_4 = np.random.uniform(size = 10)	
print("input 4: ", input_4)
input_5 = np.random.uniform(size = 10)
print("input 5: ", input_5)
input_6 = np.random.uniform(size = 10)
print("input 6: ", input_6)


input 4:  [0.35127283 0.37186885 0.9300881  0.70247436 0.09949951 0.53337057
 0.82756137 0.86960003 0.88391303 0.18186935]
input 5:  [0.41900177 0.83879152 0.31104149 0.86225089 0.14105708 0.70262058
 0.29813697 0.05089885 0.06858934 0.50114148]
input 6:  [0.72719132 0.61044171 0.59425032 0.7448641  0.53974224 0.83371677
 0.4916519  0.11333723 0.54874944 0.31263002]


In [14]:
input_5_1 = np.random.uniform(size = 10)
print("input 5.1: ", input_5_1)

input 5.1:  [0.39450592 0.54547438 0.41732544 0.50910255 0.36642327 0.99191295
 0.60738397 0.67442796 0.57184446 0.58682349]


In [64]:
# FUNCTION 2 - INPUT 4 

steepest_descent(f2,nabla_f2,input_4,tol = 10**-10,max_iterations=10000)


Number of iterations:  10000


array([0.99999048, 0.99998093, 0.99996177, 0.99992335, 0.99984633,
       0.99969191, 0.99938238, 0.99876206, 0.99751945, 0.99503264])

In [16]:
# FUNCTION 2 - INPUT 5 

steepest_descent(f2,nabla_f2,input_5,tol = 10**-10,max_iterations=100000)


Number of iterations:  45889


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
# FUNCTION 2 - INPUT 6

steepest_descent(f2,nabla_f2,input_6,tol = 10**-10,max_iterations=100000)


Number of iterations:  45331


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3)

In [66]:
# INPUT 7,8,9

input_7 = np.random.uniform(size = 2)	
print("input 7: ", input_7)
input_8 = np.random.uniform(size = 2)
print("input 8: ", input_8)
input_9 = np.random.uniform(size = 2)
print("input 9: ", input_9)
input_10 = np.random.uniform(size =2)
print("input 10: ", input_10)
input_11 = np.random.uniform(size =2)
print("input 11: ", input_11)

input 7:  [0.55127814 0.23860875]
input 8:  [0.93429044 0.85863826]
input 9:  [0.08702263 0.92536015]
input 10:  [0.87693121 0.86274073]
input 11:  [0.08245992 0.78295466]


In [68]:
# FUNCTION 3 - INPUT 7 

steepest_descent(f3,nabla_f3,input_7,tol = 10**-10,max_iterations=10000)

Number of iterations:  10000


array([3. , 0.5])

In [78]:
# FUNCTION 3 - INPUT 8

steepest_descent(f3,nabla_f3,input_8)

Number of iterations:  1659


array([2.99999997, 0.49999999])

In [79]:
# FUNCTION 3 - INPUT 9

steepest_descent(f3,nabla_f3,input_9)

Number of iterations:  1629


array([2.99999997, 0.49999999])

In [21]:
#nabla_f3(x3_star)

## Newton's Method

### Functions

In [89]:
def backtrackingStrongWolfe(c1,c2, p, s, x, d, f, nabla_f):
    """ 
    Uses strong wolfe condition
    """

    fx = f(x)
    nabla_fx = nabla_f(x)
    while f(x + s*d) > fx + c1 * s * np.dot(nabla_fx,d) and np.abs(np.dot(nabla_f(x+s*d),d)) > c2* np.abs(np.dot(nabla_fx,d)):
        s = p * s
    return s

def newtons_method(f,nabla_f, Hessian_f, x0, tol = 10**-8,max_iterations=5000):
    """ 
    input: f, nabla_f, x0 (horizontal array)
    optional input: step size sBar (default =1), 
    returns: 1 dim array for x*
    """
    
    x = x0
    k=0
    convergence_array = []

    while k < max_iterations: #and np.linalg.norm(nabla_f(x))>tol:

        convergence_array.append( round(np.linalg.norm(nabla_f(x))) )
        d = - np.linalg.inv(Hessian_f(x)) @ nabla_f(x)
        x=x + d.T        
        k+=1
        
    print("Number of iterations: ",k)
    save_results(convergence_array)
    return x

def Modified_Newtons_Method(f,nabla_f, Hessian_f, x0, tol = 10**-8,max_iterations=20000,s=1,c=0.1,p=0.5):
    """ 
    input: f, nabla_f, x0 (horizontal array)
    optional input: step size sBar (default =1), 
    returns: 1 dim array for x*
    """

    x = x0
    k=0
    while k < max_iterations and np.linalg.norm(nabla_f(x))>tol:
        
        d = - np.matmul(np.linalg.inv(Hessian_f(x)),nabla_f(x))
        s = backtracking(c, p, s, x, d, f, nabla_f)
        # print(s)
        x=x + s*d
        k+=1
    print("Number of iterations: ",k)
    return x

### Implementation

#### 1)

In [85]:
# FUNCTION 1 - METHOD 2 - INPUT 1 

newtons_method(f1,nabla_f1,Hessian_f1,input_1)

Number of iterations:  10000


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [63]:
newtons_method(f1,nabla_f1,Hessian_f1,input_2)

Number of iterations:  1


array([ 0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.])

In [64]:
newtons_method(f1,nabla_f1,Hessian_f1,input_3)

Number of iterations:  1


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
       -0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.])

#### 2)

In [77]:
# FUNCTION 2 - METHOD 
newtons_method(f2,nabla_f2,Hessian_f2,input_4)

Number of iterations:  10000


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [71]:
# FUNCTION 2 - METHOD 
newtons_method(f2,nabla_f2,Hessian_f2,input_5)

Number of iterations:  32


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [72]:
# FUNCTION 2 - METHOD 
newtons_method(f2,nabla_f2,Hessian_f2,input_6)

Number of iterations:  54


array([1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 0.99999999])

### 3.)

In [79]:
# FUNCTION 3 - METHOD 2 - INPUT 7 
newtons_method(f3,nabla_f3,Hessian_f3,input_7)
#Modified_Newtons_Method(f3,nabla_f3,Hessian_f3,input_7)

Number of iterations:  10000


array([ 0.10053794, -2.64451359])

In [85]:
# FUNCTION 3 - METHOD 2 - INPUT 8 

Modified_Newtons_Method(f3,nabla_f3,Hessian_f3,input_8)

Number of iterations:  20000


array([0.66782788, 0.43229549])

In [86]:
# FUNCTION 3 - METHOD 2 - INPUT 9 

Modified_Newtons_Method(f3,nabla_f3,Hessian_f3,input_9)

Number of iterations:  20000


array([0.31243911, 0.62779132])

In [30]:
#nabla_f3(x3_star_newtons)

In [31]:
#x3_star_mod_newtons = Modified_Newtons_Method(f3,nabla_f3,Hessian_f3,x3_0)


## Conjugate Gradient Method


### Functions

In [86]:
def backtrackingColumnVector(c, p, s, x, d, f, nabla_f):
    fx = f(x)
    nabla_fx = nabla_f(x)
    while f(x + s*d) > fx + c * s * nabla_fx.T*d:
        s = p * s
    return s

def Conjugate_Gradient_Non_Linear(f, nabla_f,x0, tol = 10**-5,maxIterations = 10000, TF_instead_of_PR = False, s=1,c=0.1,p=0.5):
    """
    f and nabla_f are functions
    Default method is Polak-Ribiere, if wishing to use Fletcher-Reeves instead, set TF_instead_of_PR to True
    x0 is a 1dim array
    returns x*
    """

    x = np.matrix(x0).T
    k = 0
    gk = nabla_f(x)
    if np.linalg.norm(gk) < tol:
        return x
    dk = -gk
    gk_1 = gk
    array = []
    while k < maxIterations: #and np.linalg.norm(gk) > tol:
        array.append(round(np.linalg.norm(gk)))
        s = backtrackingColumnVector(c, p, s, x, dk, f , nabla_f)
        # print(s)
        x0 = x
        x = x + s*dk
        gk = gk_1
        gk_1 = nabla_f(x)
        if np.linalg.norm(x-x0) == 0:
            print("Iterations: "+str(k))
            return x
        beta = (gk_1.T*(gk_1 - gk)/ (gk.T *gk))[0,0] if not TF_instead_of_PR else ((gk_1.T * gk )/ (gk.T*gk))[0,0]
        dk = -gk_1 + beta*dk
        k+=1

    save_results(array)
    print("Iterations: "+ str(k))

    return x

### Implementation

#### 1)

In [88]:
Conjugate_Gradient_Non_Linear(f1,ColumnVector_nabla_f1,input_1, maxIterations=10000).T

Iterations: 10000


matrix([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.,  0., -0., -0., -0., -0.]])

In [87]:
Conjugate_Gradient_Non_Linear(f1,ColumnVector_nabla_f1,input_2).T

Iterations: 389


matrix([[ 0.00000472,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        , -0.        , -0.        ,
         -0.        , -0.        , -0.        , -0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        , -0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        , -0.        , -0.        , -0.        , -0.        ]])

In [34]:
Conjugate_Gradient_Non_Linear(f1,ColumnVector_nabla_f1,input_3).T

Iterations: 393


matrix([[ 0.00000479,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ,  0.        ,  0.        , -0.        , -0.        ,
         -0.        , -0.        , -0.        , -0.        , -0.        ,
         -0.        , -0.        , -0.        , -0.        , -0.        ,
         -0.        , -0.        , -0.        , -0.        , -0.        ,
         -0.        , -0.        , -0.        , -0.        , -0.        ,
         -0.        , -0.        , -0.        , -0.        ,  0.        ,
          0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

#### 2)

In [35]:
# FUNCTION 2 - METHOD 3 - INPUT 4 

Conjugate_Gradient_Non_Linear(f2,ColumnVector_nabla_f2,input_4).T

Iterations: 3584


matrix([[0.99999997, 0.99999995, 0.9999999 , 0.99999979, 0.99999958,
         0.99999915, 0.99999829, 0.99999657, 0.99999312, 0.99998621]])

In [89]:
Conjugate_Gradient_Non_Linear(f2,ColumnVector_nabla_f2,input_5_1).T

Iterations: 10000


matrix([[0.99998345, 0.99996684, 0.99993353, 0.99986673, 0.99973282,
         0.99946438, 0.99892639, 0.99784856, 0.995691  , 0.99137896]])

In [37]:
Conjugate_Gradient_Non_Linear(f2,ColumnVector_nabla_f2,input_6).T

Iterations: 3614


matrix([[0.99999997, 0.99999995, 0.99999989, 0.99999979, 0.99999957,
         0.99999915, 0.99999829, 0.99999657, 0.99999311, 0.99998619]])

#### 3)

In [38]:
# FUNCTION 3 - METHOD 3 - INPUT 7

Conjugate_Gradient_Non_Linear(f3,ColumnVector_nabla_f3,input_7)


Iterations: 2


matrix([[4.32690897],
        [0.75495937]])

In [39]:
# FUNCTION 3 - METHOD 3 - INPUT 8 

Conjugate_Gradient_Non_Linear(f3,ColumnVector_nabla_f3,input_8)


Iterations: 3


matrix([[5.14269234],
        [0.77572598]])

In [40]:
# FUNCTION 3 - METHOD 3 - INPUT 9 

Conjugate_Gradient_Non_Linear(f3,ColumnVector_nabla_f3,input_9)


Iterations: 908


matrix([[2.99996819],
        [0.49999206]])

In [41]:
Conjugate_Gradient_Non_Linear(f3,ColumnVector_nabla_f3,input_10)

Iterations: 263


matrix([[2.9999746 ],
        [0.49999377]])

In [42]:
Conjugate_Gradient_Non_Linear(f3,ColumnVector_nabla_f3,input_11)

Iterations: 1003


matrix([[2.99996838],
        [0.49999211]])

## Quasi Newton Method

### Functions

In [43]:
def rank_two(Hk, gk, gk_1, xk, xk_1, ck=1):
    delta_k = xk_1 - xk
    gamma_k = gk_1-gk

    qk = delta_k / (delta_k.T @ gamma_k).item() - Hk @ gamma_k / (gamma_k.T @ Hk @ gamma_k).item()
    
    term1 = delta_k@delta_k.T /(delta_k.T @ gamma_k).item()

    term2 = Hk@gamma_k @(Hk@gamma_k).T/ (gamma_k.T @ Hk @ gamma_k).item()

    term3 = ck * (gamma_k.T@Hk@gamma_k).item() * qk@qk.T
    
    return Hk + term1 -  term2 + term3


def quasi_newton(f, nabla_f,x0, tol = 10**-5,max_iterations = 10000,p = 0.5,s = 1,c = 0.1):
    xk = np.matrix(x0).T
    Hk = np.eye(len(x0))

    xk_1 = xk
    gk_1 = np.matrix(nabla_f(xk_1))
    k=0
    array = []

    while k < max_iterations: #(np.linalg.norm(xk_1-xk) > tol or k==0) and 
        
        array.append( round(np.linalg.norm(xk_1-xk)) )
        xk= xk_1
        gk = gk_1
        dk = -(Hk@gk)
        sk = backtrackingColumnVector(c, p, s, xk, dk, f, nabla_f)
        
        xk_1 = xk + sk * dk
        gk_1 = np.matrix(nabla_f(xk_1))
        Hk = rank_two(Hk, gk, gk_1, xk, xk_1) 
        k+=1

    print("Number of iterations: " + str(k))
    return xk

### Implementation

#### 1)

In [44]:
quasi_newton(f1,ColumnVector_nabla_f1,input_1).T

Number of iterations: 61


matrix([[ 0.00000312,  0.00000003,  0.00000007,  0.00000023, -0.00000003,
          0.00000007,  0.00000012, -0.00000015,  0.00000007,  0.00000029,
          0.00000005,  0.00000015,  0.00000001,  0.00000038,  0.00000009,
          0.00000004,  0.00000018, -0.00000005,  0.00000018, -0.00000015,
          0.00000023,  0.0000001 ,  0.00000008,  0.0000003 , -0.00000011,
          0.00000023, -0.00000032,  0.00000003,  0.00000011, -0.00000027,
          0.00000011,  0.00000006,  0.        ,  0.00000005,  0.00000005,
          0.00000011,  0.00000005,  0.00000002,  0.00000002,  0.00000005,
         -0.        ,  0.00000001, -0.        , -0.00000003, -0.00000003,
          0.00000007,  0.00000005,  0.00000001, -0.00000001, -0.00000005]])

In [45]:
quasi_newton(f1,ColumnVector_nabla_f1,input_2).T

Number of iterations: 59


matrix([[ 0.00000022, -0.00000005,  0.00000002, -0.00000003,  0.00000001,
          0.00000001, -0.00000002,  0.00000007,  0.00000002,  0.00000002,
          0.00000001, -0.00000004, -0.00000012, -0.00000014,  0.00000047,
         -0.00000001, -0.00000003, -0.00000005,  0.00000011, -0.00000013,
          0.00000008, -0.00000009,  0.00000003, -0.00000011,  0.00000005,
         -0.        , -0.00000004, -0.00000003,  0.00000009, -0.00000008,
          0.00000011, -0.00000002, -0.00000003, -0.00000002, -0.00000002,
          0.00000002, -0.00000001, -0.00000003,  0.00000002, -0.00000001,
         -0.00000004,  0.00000002,  0.00000004, -0.00000001, -0.00000002,
          0.00000002, -0.00000003, -0.00000001, -0.00000002,  0.00000002]])

In [46]:
quasi_newton(f1,ColumnVector_nabla_f1,input_3).T

Number of iterations: 60


matrix([[-0.00000336, -0.00000043,  0.00000014, -0.00000001, -0.00000037,
          0.00000005, -0.00000002,  0.00000027, -0.00000004, -0.00000018,
          0.00000022,  0.00000012,  0.00000003,  0.        ,  0.00000008,
          0.00000008,  0.00000018, -0.00000011, -0.00000009,  0.00000015,
         -0.00000001, -0.00000002,  0.0000003 ,  0.00000009,  0.00000001,
          0.00000013,  0.00000009, -0.00000008,  0.0000002 ,  0.00000011,
          0.00000004, -0.00000005, -0.00000004, -0.00000004, -0.0000003 ,
         -0.00000014,  0.00000013,  0.00000001, -0.00000008,  0.00000019,
          0.00000022,  0.00000001, -0.00000007,  0.00000007,  0.00000006,
         -0.0000001 , -0.00000008, -0.00000016,  0.00000005, -0.00000002]])

#### 2)

In [47]:
quasi_newton(f2,ColumnVector_nabla_f2,input_4).T


Number of iterations: 63


matrix([[1.00000012, 0.99999994, 1.00000003, 1.00000004, 0.99999978,
         0.99999959, 0.99999941, 0.99999946, 0.99999912, 0.99999824]])

In [48]:
quasi_newton(f2,ColumnVector_nabla_f2,input_5).T

Number of iterations: 60


matrix([[1.00000022, 1.        , 0.99999986, 1.00000006, 0.99999988,
         1.00000005, 0.99999995, 0.99999986, 0.99999962, 0.99999902]])

In [49]:
quasi_newton(f2,ColumnVector_nabla_f2,input_6).T


Number of iterations: 65


matrix([[0.99999998, 0.99999997, 0.99999987, 1.00000001, 1.00000015,
         1.00000019, 0.99999999, 0.99999995, 0.9999999 , 0.99999962]])

#### 3)

In [50]:
quasi_newton(f3,ColumnVector_nabla_f3,input_7).T

Number of iterations: 17


matrix([[2.99999931, 0.49999995]])

In [51]:
quasi_newton(f3,ColumnVector_nabla_f3,input_8).T

Number of iterations: 16


matrix([[2.99999975, 0.49999993]])

In [52]:
quasi_newton(f3,ColumnVector_nabla_f3,input_9).T

Number of iterations: 13


matrix([[2.99999948, 0.49999986]])

### Functions

In [53]:
def rank_two(Hk, gk, gk_1, xk, xk_1, ck=1):
    delta_k = xk_1 - xk
    gamma_k = gk_1-gk

    qk = delta_k / (delta_k.T @ gamma_k).item() - Hk @ gamma_k / (gamma_k.T @ Hk @ gamma_k).item()
    
    term1 = delta_k@delta_k.T /(delta_k.T @ gamma_k).item()

    term2 = Hk@gamma_k @(Hk@gamma_k).T/ (gamma_k.T @ Hk @ gamma_k).item()

    term3 = ck * (gamma_k.T@Hk@gamma_k).item() * qk@qk.T
    
    return Hk + term1 -  term2 + term3


def quasi_newton(f, nabla_f,x0, tol = 10**-5,max_iterations = 10000,p = 0.5,s = 1,c = 0.1):
    xk = np.matrix(x0).T
    Hk = np.eye(len(x0))

    xk_1 = xk
    gk_1 = np.matrix(nabla_f(xk_1))
    k=0
    while (np.linalg.norm(xk_1-xk) > tol or k==0) and k < max_iterations :
        xk= xk_1
        gk = gk_1
        dk = -(Hk@gk)
        sk = backtrackingColumnVector(c, p, s, xk, dk, f, nabla_f)
        
        xk_1 = xk + sk * dk
        gk_1 = np.matrix(nabla_f(xk_1))
        Hk = rank_two(Hk, gk, gk_1, xk, xk_1) 
        k+=1
    print("Number of iterations: " + str(k))
    return xk

### Implementation

#### 1)

In [54]:
quasi_newton(f1,ColumnVector_nabla_f1,input_1).T

Number of iterations: 61


matrix([[ 0.00000312,  0.00000003,  0.00000007,  0.00000023, -0.00000003,
          0.00000007,  0.00000012, -0.00000015,  0.00000007,  0.00000029,
          0.00000005,  0.00000015,  0.00000001,  0.00000038,  0.00000009,
          0.00000004,  0.00000018, -0.00000005,  0.00000018, -0.00000015,
          0.00000023,  0.0000001 ,  0.00000008,  0.0000003 , -0.00000011,
          0.00000023, -0.00000032,  0.00000003,  0.00000011, -0.00000027,
          0.00000011,  0.00000006,  0.        ,  0.00000005,  0.00000005,
          0.00000011,  0.00000005,  0.00000002,  0.00000002,  0.00000005,
         -0.        ,  0.00000001, -0.        , -0.00000003, -0.00000003,
          0.00000007,  0.00000005,  0.00000001, -0.00000001, -0.00000005]])

In [55]:
quasi_newton(f1,ColumnVector_nabla_f1,input_2).T

Number of iterations: 59


matrix([[ 0.00000022, -0.00000005,  0.00000002, -0.00000003,  0.00000001,
          0.00000001, -0.00000002,  0.00000007,  0.00000002,  0.00000002,
          0.00000001, -0.00000004, -0.00000012, -0.00000014,  0.00000047,
         -0.00000001, -0.00000003, -0.00000005,  0.00000011, -0.00000013,
          0.00000008, -0.00000009,  0.00000003, -0.00000011,  0.00000005,
         -0.        , -0.00000004, -0.00000003,  0.00000009, -0.00000008,
          0.00000011, -0.00000002, -0.00000003, -0.00000002, -0.00000002,
          0.00000002, -0.00000001, -0.00000003,  0.00000002, -0.00000001,
         -0.00000004,  0.00000002,  0.00000004, -0.00000001, -0.00000002,
          0.00000002, -0.00000003, -0.00000001, -0.00000002,  0.00000002]])

In [56]:
quasi_newton(f1,ColumnVector_nabla_f1,input_3).T

Number of iterations: 60


matrix([[-0.00000336, -0.00000043,  0.00000014, -0.00000001, -0.00000037,
          0.00000005, -0.00000002,  0.00000027, -0.00000004, -0.00000018,
          0.00000022,  0.00000012,  0.00000003,  0.        ,  0.00000008,
          0.00000008,  0.00000018, -0.00000011, -0.00000009,  0.00000015,
         -0.00000001, -0.00000002,  0.0000003 ,  0.00000009,  0.00000001,
          0.00000013,  0.00000009, -0.00000008,  0.0000002 ,  0.00000011,
          0.00000004, -0.00000005, -0.00000004, -0.00000004, -0.0000003 ,
         -0.00000014,  0.00000013,  0.00000001, -0.00000008,  0.00000019,
          0.00000022,  0.00000001, -0.00000007,  0.00000007,  0.00000006,
         -0.0000001 , -0.00000008, -0.00000016,  0.00000005, -0.00000002]])

#### 2)

In [57]:
quasi_newton(f2,ColumnVector_nabla_f2,input_4).T


Number of iterations: 63


matrix([[1.00000012, 0.99999994, 1.00000003, 1.00000004, 0.99999978,
         0.99999959, 0.99999941, 0.99999946, 0.99999912, 0.99999824]])

In [58]:
quasi_newton(f2,ColumnVector_nabla_f2,input_5).T

Number of iterations: 60


matrix([[1.00000022, 1.        , 0.99999986, 1.00000006, 0.99999988,
         1.00000005, 0.99999995, 0.99999986, 0.99999962, 0.99999902]])

In [59]:
quasi_newton(f2,ColumnVector_nabla_f2,input_6).T


Number of iterations: 65


matrix([[0.99999998, 0.99999997, 0.99999987, 1.00000001, 1.00000015,
         1.00000019, 0.99999999, 0.99999995, 0.9999999 , 0.99999962]])

#### 3)

In [60]:
quasi_newton(f3,ColumnVector_nabla_f3,input_7).T

Number of iterations: 17


matrix([[2.99999931, 0.49999995]])

In [61]:
quasi_newton(f3,ColumnVector_nabla_f3,input_8).T

Number of iterations: 16


matrix([[2.99999975, 0.49999993]])

In [62]:
quasi_newton(f3,ColumnVector_nabla_f3,input_9).T

Number of iterations: 13


matrix([[2.99999948, 0.49999986]])